services:
  postgres:
    image: postgres:15-alpine
    container_name: huddle_postgres
    environment:
      POSTGRES_DB: huddle
      POSTGRES_USER: huddle_user
      POSTGRES_PASSWORD: huddle_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - huddle_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: huddle_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - huddle_network
    restart: unless-stopped
    command: redis-server --appendonly yes

  minio:
    image: minio/minio:latest
    container_name: huddle_minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - huddle_network
    restart: unless-stopped
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local

networks:
  huddle_network:
    driver: bridge
